spring:
  application:
    name: gateway-examples
  cloud:
    gateway:
      routes:
        - id: springmvc # 声明一个路由转发规则。仅转发请求，无聚合处理功能
          predicates:
            - Path=/springmvc-api/** # 请求前缀
          uri: http://localhost:8080 # 转发地址
          filters:
            - name: Springmvc # 按过滤器命名规则，指定此转发规则单独的过滤器。SpringmvcGatewayFilterFactory过滤器
            - StripPrefix=1 # 转发时将去掉path路径前缀，/springmvc-api/
            - PrefixPath=/api/ # 添加/api/前缀

  jackson:
    default-property-inclusion: non_null
server:
  port: 80

logging:
  level:
    root: warn
    com:
      example: debug

springmvc-server: http://localhost:8080/api/